services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend.dev
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
