services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend.prod
    ports:
      - "3000:3000"
    environment:      
      - REACT_APP_API_URL=http://backend:8000
    command: ["serve", "-s", "build", "-l", "3000", "--single"]   # explicitly override command to production serve
    volumes: []  # override volumes to empty list to remove dev mounts  

