"""Add role column to User

Revision ID: 205a79a6e792
Revises: 66df03e9f602
Create Date: 2025-06-14 14:10:38.057391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205a79a6e792'
down_revision: Union[str, None] = '66df03e9f602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False,server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
   
    # ### end Alembic commands ###
