"""Add user_friendly_name to saved_digipins

Revision ID: c553fd2a6797
Revises: ca7d491c832b
Create Date: 2025-06-08 10:32:47.797206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c553fd2a6797'
down_revision: Union[str, None] = 'ca7d491c832b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_digipins', sa.Column('user_friendly_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_digipins', 'user_friendly_name')
    # ### end Alembic commands ###
