"""Add is_oauth column to users

Revision ID: ca7d491c832b
Revises: e41477d40afd
Create Date: 2025-06-08 05:09:20.537453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7d491c832b'
down_revision: Union[str, None] = 'e41477d40afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_digipins', 'is_oauth')
    op.add_column('users', sa.Column('is_oauth', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_oauth')
    op.add_column('saved_digipins', sa.Column('is_oauth', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
