"""Add is_oauth column to users

Revision ID: e41477d40afd
Revises: 076f7f855d09
Create Date: 2025-06-08 05:07:40.309755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41477d40afd'
down_revision: Union[str, None] = '076f7f855d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_digipins', sa.Column('is_oauth', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_digipins', 'is_oauth')
    # ### end Alembic commands ###
